FROM ubuntu:18.04
RUN apt-get update
RUN apt-get -qy install wget
RUN wget "https://apt.puppet.com/puppet-release-bionic.deb" -P /tmp
RUN dpkg -i "/tmp/puppet-release-bionic.deb"
RUN apt-get update
RUN apt-get install puppet-agent
# change certname to puppet.agent
RUN echo "certname=puppet.agent" >> /etc/puppetlabs/puppet/puppet.conf
RUN /opt/puppetlabs/bin/puppet agent --no-daemonize -t
CMD ["/opt/puppetlabs/bin/puppet", "agent", "--no-daemonize", "--debug"]
